Assignment6.2
UWC2-APIDOC/to-do-service-au24 pull request #22
Opened 2024-10-28 21:09 UTC by SophieLAPIDOC

2024-11-06 15:20 UTC, rbwatson commented
Rebased the PR/feature branch with the current version of the `main` branch.

2024-11-06 15:33 UTC, rbwatson requested changes
I like the idea of this topic, but it's not a quick start topic.

This topic is written as more of a visualization of what your (the customer's) app could look like after you've integrated the to-do-service into it.

So, instead of calling it a quickstart, call it a _use-case example_ of how the service would look when integrated into an app. Then conclude by linking them to a quickstart or one of the **Add new user** or **Add new task** topics to show how they can start using it

2024-11-06 15:33 UTC, rbwatson commented on docs/first-use_SophieL.md
> +To use the To-Do service, you need a user account. Read all about it in our first tutorial [Enrol a new user](https://uwc2-apidoc.github.io/to-do-service-au24/tutorials/enroll-a-new-user.html).
```suggestion
To use the To-Do service, you need a user account. Read all about it in our first tutorial [Enroll a new user](https://uwc2-apidoc.github.io/to-do-service-au24/tutorials/enroll-a-new-user.html).

```

2024-11-06 15:33 UTC, rbwatson commented on docs/first-use_SophieL.md
> +YOu can raise your cup to that.
```suggestion
You can raise your cup to that.

```

2024-11-06 15:33 UTC, rbwatson commented on docs/index.md
I added your topic to the overview/landing page to make it accessible.

2024-11-06 15:35 UTC, rbwatson commented
A great topic!

Review the comments in the review and update your topic. Build and test your updated topics, squash the commits so there's only one and re-request a review.

2024-11-07 10:01 UTC, closed without merging

2024-11-07 10:07 UTC, SophieLAPIDOC commented
Hi Rob, please review. I have accepted your suggestions, then squashed commits via GitHub desktop. I will wait for your feedback before attempting to modify assignment 6.1. Hopefully, I have not destroyed everybody's work.

2024-11-07 10:07 UTC, SophieLAPIDOC commented
Hi Rob, please review. I have accepted your suggestions, then squashed commits via GitHub desktop. I will wait for your feedback before attempting to modify assignment 6.1. Hopefully, I have not destroyed everybody's work.