added new 'create user' tutorial
UWC2-APIDOC/to-do-service-au24 pull request #25
Opened 2024-10-29 01:01 UTC by dougmanis

changes:
* added new 'add-a-user_dmanis.md' tutorial file
* added link to the new tutorial from the existing docs index topic
* supporting assignment 6.2: 'Write a first use or a tutorial topic'

2024-11-06 15:52 UTC, rbwatson commented
Rebased PR branch to current `main` branch.

2024-11-06 19:11 UTC, rbwatson requested changes
This looks very good!

See my review comments for more details.
After you have addressed the comments and the built documentation looks good, squash the commits in the PR and re-request a review so I can finish the merge.

2024-11-06 19:11 UTC, rbwatson commented on docs/tutorials/add-a-user_dmanis.md
> +This tutorial will teach you how to add a new user to the To-Do system.
You're underselling your tutorial--it's doing much more!

You should have an overview that describes the big picture, and how the procedures that follow support the overall goal.

2024-11-06 19:11 UTC, rbwatson commented on docs/tutorials/add-a-user_dmanis.md
> +## Steps
This section would be a good place to describe the procedures that follow and how they contribute to the overall goal.

Then make each procedure an H3 (`###`) with a title that describes the procedure goal (as the following sections do).

2024-11-06 19:11 UTC, rbwatson commented on docs/tutorials/add-a-user_dmanis.md
> +## Fetch your user's details
```suggestion
### Fetch your new user's details 
```

2024-11-06 19:11 UTC, rbwatson commented on docs/tutorials/add-a-user_dmanis.md
> +You can fetch your user's details any time with the GET method of the 'users' resource with the unique ID set by the server.
```suggestion
You can fetch your user's details any time with the GET method of the 'users' resource and the instance's unique ID. 
```

2024-11-06 19:11 UTC, rbwatson commented on docs/tutorials/add-a-user_dmanis.md
> +## Fetch details for all users in the system
I'm not sure how this is part of adding a new user.

This should be explained in the `Steps` section or removed.

2024-11-06 19:11 UTC, rbwatson commented on docs/index.md
I moved your new link to the Tutorials section of the topic.

2024-11-08 23:06 UTC, dougmanis commented
> r

Bob I am thrashing in GitHub commit land. I might need help before I make more of a mess. 

I think what happened: 
* I think I must have pulled from branch 6.2-tutorial-dmanis branch to pick up your minor edits 
* My local Git prompted me to resolve some merge conflicts, which I did and then committed and pushed up to GitHub along with my own editorial changes 
* Now I have _merge_ commits, which cannot be squashed(?) 

I've attempted to roll back the merge commits and I'm just making a mess of more merges and commits and I'm getting lost. 

What can I do to clean up mess of commits so that I can give you one clean commit with only the editorial changes in it?

2024-11-08 23:36 UTC, rbwatson commented
I'm sorry to hear you're having trouble.

When you think you've twisted your PR into a Gordian knot, you can try to pull your commits from the tangled PR and cherry-pick them over to a fresh branch. You'll have to create a new PR from the fresh branch, but that'll save your work and make the tangles disappear.

I think the easiest path to take at that point is:
1. In the GitHub website, update your fork.
2. In the GitHub desktop, create a new feature branch from `main`.
3. Select your PR/feature branch.
4. Select the commit(s) from your PR branch with your changes. Don't select any of the merge commits or any other commits. You can tell which commits are yours by using the compare branches option at the top of the commits in GitHub Desktop. 
5. [Cherry-pick that/those commit(s)](https://docs.github.com/en/desktop/managing-commits/cherry-picking-a-commit-in-github-desktop) from your PR branch to your new feature branch.
6. Review the changes in your new feature branch. Build and test the docs from your new feature branch.
7. After everything looks good, open a new PR from the new feature branch. Reference your old/broken PR in your PR description.
8. Update this PR with a new comment that contains the link to your new PR.
9. Let me know at this point by selecting the re-request review in the Reviewers column and I'll take it from there.

Your changes should be able to be cherry-picked from this branch to a new one without any problems.

2024-11-12 03:25 UTC, dougmanis commented
Notes:
* This pull request is superseded by request #58 
* This request had some branching and merging issues so I cherry picked the changes to a new branch and new pull request

2024-11-14 00:02 UTC, rbwatson commented
This PR was replaced by #58, which was merged and closed.

2024-11-14 00:02 UTC, closed without merging