LandingPage
UWC2-APIDOC/to-do-service-au24 pull request #28
Opened 2024-10-29 03:34 UTC by wfish-ghoti

Assignment 6.1

2024-11-04 21:32 UTC, rbwatson commented
rebased PR to include current `main` branch

2024-11-04 22:39 UTC, rbwatson requested changes
Please try to use more markdown and less HTML in the topic source code.

2024-11-04 23:40 UTC, wfish-ghoti commented
> Please try to use more markdown and less HTML in the topic source code.

Hi Bob, I'm sorry. I thought you said that HTML was okay to use for this assignment. 
<img width="852" alt="image" src="https://github.com/user-attachments/assets/a64c442e-612b-4130-9fab-c8533bc0e596">

Would you like me to redo in md only?

2024-11-13 23:13 UTC, rbwatson commented
Squashed commits and rebased to current `main` branch.

2024-11-13 23:39 UTC, rbwatson commented
Fixed some links that had changed since PR was made.
Squashed all commits & rebased.

2024-11-13 23:40 UTC, rbwatson commented on docs/Overview_wuf.md
> +Our [Quickstart Guide](Quickstart_wuf.md) will get you up and running in **15 minutes**! Plus, we've got tutorials to help you out with whatever you need.
Changed link to markdown link.

2024-11-13 23:40 UTC, rbwatson commented on docs/contactus.md
> +* Chat with us: **opens-fake-chat-window**
Removed fake link to pass CI test

2024-11-13 23:41 UTC, rbwatson commented on docs/index.md
> +* [Wendy Fish's overview](Overview_wuf.md)
Added link to new overview in index.md.

2024-11-13 23:41 UTC, rbwatson approved these changes
LGTM.

2024-11-13 23:41 UTC, merged